spring:
  application:
    name: ai-agent-service

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

langchain4j:
  google-ai:
    api-key: ${GEMINI_API_KEY}
    model-name: gemini-2.5-flash-lite

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    com.lumadesk.ai_agent_service: DEBUG
  file:
    name: "C:\\Users\\balaji.vs\\IdeaProjects\\LumaDesk\\LumaDesk-microservices\\Application-Logs\\ai-agent-service.log"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [${spring.application.name}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [${spring.application.name}] %logger{36} - %msg%n"